; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs =  pibot_cnc_pendant
src_dir     = src
build_dir   = .pioenvs
lib_dir     = libraries
libdeps_dir = .piolibdeps

[env:pibot_cnc_pendant]
; Arduino  core 3.0.4 - IDF 5.1.4
platform = https://github.com/pioarduino/platform-espressif32/releases/download/51.03.04/platform-espressif32.zip
board = esp32dev
framework = arduino
monitor_speed = 115200
monitor_echo = yes
monitor_filters = send_on_enter, colorize, esp32_exception_decoder
upload_speed=921600
board_build.filesystem = littlefs
build_flags =
    -DJSP_USE_CHARP
    -DE4_POS_T
    -DVERBATIM_GCODE_MODES
    -DFNC_BAUD=1000000
    -DCORE_DEBUG_LEVEL=0

